### ISSUE TITLE
Wireframe tool

### ISSUE THREAD

**Issue by cachedout** [ZimboPy/zimfarm#10]
We need to decide what tool to use for wireframing. It should be something free to download and use and easy for everybody to modify any proposed wireframes.

Does anybody have a suggestion on this?

**Comment by cachedout** [comment]
@V0idExp has suggested [draw.io](http://draw.io) for this in the Slack channel.

**Comment by ronnzw** [comment]
https://www.draw.io/ looks ok to me.i think we should go ahead with it.Unless one has another option?
